import puppeteer from "puppeteer";
import * as XLSX from "xlsx";

// ---- CONFIG ----
const FORM_URL = "https://form.jotform.com/252180486223454";
const XLSX_FILE = "submissions.xlsx"; 

// Map Excel headers → JotForm field names
// (you’ll need to inspect the form HTML to confirm field `name` attributes)
const FIELD_MAP = {
  "First": "q5_first5",   // Example mapping
  "Middle": "q6_middle",
  "Last": "q7_last7",
  "Suffix": "q8_suffix",
  "MM": "q10_mm",
  "DD": "q11_dd",
  "YYYY": "q12_yyyy",
  "Sets": "q17_sets",
  "Pieces": "q18_pieces",
  "Turnout Gears Details >> 1 >> Type of Turnout Gear": "q66_typeA66[0][0]",
  "Turnout Gears Details >> 1 >> Year of Use (Start)": "q66_typeA66[0][1]",
  "Turnout Gears Details >> 1 >> Year of Use (End)": "q66_typeA66[0][2]",
  "Turnout Gears Details >> 1 >> Description of Turnout Gear": "q66_typeA66[0][3]",
  "Turnout Gears Details >> 1 >> Manufacturer": "q66_typeA66[0][4]",
  "Turnout Gears Details >> 1 >> Do you have this TOG ? (Yes)": "q66_typeA66[0][5]",
  "Turnout Gears Details >> 1 >> Do you have this TOG ? (No)": "q66_typeA66[0][6]",
  "Turnout Gears Details >> 2 >> Type of Turnout Gear": "q66_typeA66[1][0]",
  "Turnout Gears Details >> 2 >> Year of Use (Start)": "q66_typeA66[1][1]",
  "Turnout Gears Details >> 2 >> Year of Use (End)": "q66_typeA66[1][2]",
  "Turnout Gears Details >> 2 >> Description of Turnout Gear": "q66_typeA66[1][3]",
  "Turnout Gears Details >> 2 >> Manufacturer": "q66_typeA66[1][4]",
  "Turnout Gears Details >> 2 >> Do you have this TOG ? (Yes)": "q66_typeA66[1][5]",
  "Turnout Gears Details >> 2 >> Do you have this TOG ? (No)": "q66_typeA66[1][6]",
  "Turnout Gears Details >> 3 >> Type of Turnout Gear": "q66_typeA66[2][0]",
  "Turnout Gears Details >> 3 >> Year of Use (Start)": "q66_typeA66[2][1]",
  "Turnout Gears Details >> 3 >> Year of Use (End)": "q66_typeA66[2][2]",
  "Turnout Gears Details >> 3 >> Description of Turnout Gear": "q66_typeA66[2][3]",
  "Turnout Gears Details >> 3 >> Manufacturer": "q66_typeA66[2][4]",
  "Turnout Gears Details >> 3 >> Do you have this TOG ? (Yes)": "q66_typeA66[2][5]",
  "Turnout Gears Details >> 3 >> Do you have this TOG ? (No)": "q66_typeA66[2][6]",
  "Turnout Gears Details >> 4 >> Type of Turnout Gear": "q66_typeA66[3][0]",
  "Turnout Gears Details >> 4 >> Year of Use (Start)": "q66_typeA66[3][1]",
  "Turnout Gears Details >> 4 >> Year of Use (End)": "q66_typeA66[3][2]",
  "Turnout Gears Details >> 4 >> Description of Turnout Gear": "q66_typeA66[3][3]",
  "Turnout Gears Details >> 4 >> Manufacturer": "q66_typeA66[3][4]",
  "Turnout Gears Details >> 4 >> Do you have this TOG ? (Yes)": "q66_typeA66[3][5]",
  "Turnout Gears Details >> 4 >> Do you have this TOG ? (No)": "q66_typeA66[3][6]",
  "Turnout Gears Details >> 5 >> Type of Turnout Gear": "q66_typeA66[4][0]",
  "Turnout Gears Details >> 5 >> Year of Use (Start)": "q66_typeA66[4][1]",
  "Turnout Gears Details >> 5 >> Year of Use (End)": "q66_typeA66[4][2]",
  "Turnout Gears Details >> 5 >> Description of Turnout Gear": "q66_typeA66[4][3]",
  "Turnout Gears Details >> 5 >> Manufacturer": "q66_typeA66[4][4]",
  "Turnout Gears Details >> 5 >> Do you have this TOG ? (Yes)": "q66_typeA66[4][5]",
  "Turnout Gears Details >> 5 >> Do you have this TOG ? (No)": "q66_typeA66[4][6]",
  "Turnout Gears Details >> 6 >> Type of Turnout Gear": "q66_typeA66[5][0]",
  "Turnout Gears Details >> 6 >> Year of Use (Start)": "q66_typeA66[5][1]",
  "Turnout Gears Details >> 6 >> Year of Use (End)": "q66_typeA66[5][2]",
  "Turnout Gears Details >> 6 >> Description of Turnout Gear": "q66_typeA66[5][3]",
  "Turnout Gears Details >> 6 >> Manufacturer": "q66_typeA66[5][4]",
  "Turnout Gears Details >> 6 >> Do you have this TOG ? (Yes)": "q66_typeA66[5][5]",
  "Turnout Gears Details >> 6 >> Do you have this TOG ? (No)": "q66_typeA66[5][6]",
  "Turnout Gears Details >> 7 >> Type of Turnout Gear": "q66_typeA66[6][0]",
  "Turnout Gears Details >> 7 >> Year of Use (Start)": "q66_typeA66[6][1]",
  "Turnout Gears Details >> 7 >> Year of Use (End)": "q66_typeA66[6][2]",
  "Turnout Gears Details >> 7 >> Description of Turnout Gear": "q66_typeA66[6][3]",
  "Turnout Gears Details >> 7 >> Manufacturer": "q66_typeA66[6][4]",
  "Turnout Gears Details >> 7 >> Do you have this TOG ? (Yes)": "q66_typeA66[6][5]",
  "Turnout Gears Details >> 7 >> Do you have this TOG ? (No)": "q66_typeA66[6][6]",
  "Turnout Gears Details >> 8 >> Type of Turnout Gear": "q66_typeA66[7][0]",
  "Turnout Gears Details >> 8 >> Year of Use (Start)": "q66_typeA66[7][1]",
  "Turnout Gears Details >> 8 >> Year of Use (End)": "q66_typeA66[7][2]",
  "Turnout Gears Details >> 8 >> Description of Turnout Gear": "q66_typeA66[7][3]",
  "Turnout Gears Details >> 8 >> Manufacturer": "q66_typeA66[7][4]",
  "Turnout Gears Details >> 8 >> Do you have this TOG ? (Yes)": "q66_typeA66[7][5]",
  "Turnout Gears Details >> 8 >> Do you have this TOG ? (No)": "q66_typeA66[7][6]",
  "Turnout Gears Details >> 9 >> Type of Turnout Gear": "q66_typeA66[8][0]",
  "Turnout Gears Details >> 9 >> Year of Use (Start)": "q66_typeA66[8][1]",
  "Turnout Gears Details >> 9 >> Year of Use (End)": "q66_typeA66[8][2]",
  "Turnout Gears Details >> 9 >> Description of Turnout Gear": "q66_typeA66[8][3]",
  "Turnout Gears Details >> 9 >> Manufacturer": "q66_typeA66[8][4]",
  "Turnout Gears Details >> 9 >> Do you have this TOG ? (Yes)": "q66_typeA66[8][5]",
  "Turnout Gears Details >> 9 >> Do you have this TOG ? (No)": "q66_typeA66[8][6]",
  "Turnout Gear Provider Details >> 1 >> Type of Turnout Gear": "q64_turnoutGear[0][0]",
  "Turnout Gear Provider Details >> 1 >> Provider Name": "q64_turnoutGear[0][1]",
  "Turnout Gear Provider Details >> 1 >> Provider Address": "q64_turnoutGear[0][2]",
  "Turnout Gear Provider Details >> 2 >> Type of Turnout Gear": "q64_turnoutGear[1][0]",
  "Turnout Gear Provider Details >> 2 >> Provider Name": "q64_turnoutGear[1][1]",
  "Turnout Gear Provider Details >> 2 >> Provider Address": "q64_turnoutGear[1][2]",
  "Turnout Gear Provider Details >> 3 >> Type of Turnout Gear": "q64_turnoutGear[2][0]",
  "Turnout Gear Provider Details >> 3 >> Provider Name": "q64_turnoutGear[2][1]",
  "Turnout Gear Provider Details >> 3 >> Provider Address": "q64_turnoutGear[2][2]",
  "Turnout Gear Provider Details >> 4 >> Type of Turnout Gear": "q64_turnoutGear[3][0]",
  "Turnout Gear Provider Details >> 4 >> Provider Name": "q64_turnoutGear[3][1]",
  "Turnout Gear Provider Details >> 4 >> Provider Address": "q64_turnoutGear[3][2]",
  "Turnout Gear Provider Details >> 5 >> Type of Turnout Gear": "q64_turnoutGear[4][0]",
  "Turnout Gear Provider Details >> 5 >> Provider Name": "q64_turnoutGear[4][1]",
  "Turnout Gear Provider Details >> 5 >> Provider Address": "q64_turnoutGear[4][2]",
  "Turnout Gear Provider Details >> 6 >> Type of Turnout Gear": "q64_turnoutGear[5][0]",
  "Turnout Gear Provider Details >> 6 >> Provider Name": "q64_turnoutGear[5][1]",
  "Turnout Gear Provider Details >> 6 >> Provider Address": "q64_turnoutGear[5][2]",
  "Turnout Gear Provider Details >> 7 >> Type of Turnout Gear": "q64_turnoutGear[6][0]",
  "Turnout Gear Provider Details >> 7 >> Provider Name": "q64_turnoutGear[6][1]",
  "Turnout Gear Provider Details >> 7 >> Provider Address": "q64_turnoutGear[6][2]",
  "Turnout Gear Provider Details >> 8 >> Type of Turnout Gear": "q64_turnoutGear[7][0]",
  "Turnout Gear Provider Details >> 8 >> Provider Name": "q64_turnoutGear[7][1]",
  "Turnout Gear Provider Details >> 8 >> Provider Address": "q64_turnoutGear[7][2]",
  "Turnout Gear Provider Details >> 9 >> Type of Turnout Gear": "q64_turnoutGear[8][0]",
  "Turnout Gear Provider Details >> 9 >> Provider Name": "q64_turnoutGear[8][1]",
  "Turnout Gear Provider Details >> 9 >> Provider Address": "q64_turnoutGear[8][2]",
  "Turnout Gear Uses >> 1 >> Type of Turnout Gear": "q63_turnoutGear63[0][0]",
  "Turnout Gear Uses >> 1 >> Circumstances of Use": "q63_turnoutGear63[0][1]",
  "Turnout Gear Uses >> 1 >> Year (End)": "q63_turnoutGear63[0][2]",
  "Turnout Gear Uses >> 2 >> Type of Turnout Gear": "q63_turnoutGear63[1][0]",
  "Turnout Gear Uses >> 2 >> Circumstances of Use": "q63_turnoutGear63[1][1]",
  "Turnout Gear Uses >> 2 >> Year (End)": "q63_turnoutGear63[1][2]",
  "Turnout Gear Uses >> 3 >> Type of Turnout Gear": "q63_turnoutGear63[2][0]",
  "Turnout Gear Uses >> 3 >> Circumstances of Use": "q63_turnoutGear63[2][1]",
  "Turnout Gear Uses >> 3 >> Year (End)": "q63_turnoutGear63[2][2]",
  "Turnout Gear Uses >> 4 >> Type of Turnout Gear": "q63_turnoutGear63[3][0]",
  "Turnout Gear Uses >> 4 >> Circumstances of Use": "q63_turnoutGear63[3][1]",
  "Turnout Gear Uses >> 4 >> Year (End)": "q63_turnoutGear63[3][2]",
  "Turnout Gear Uses >> 5 >> Type of Turnout Gear": "q63_turnoutGear63[4][0]",
  "Turnout Gear Uses >> 5 >> Circumstances of Use": "q63_turnoutGear63[4][1]",
  "Turnout Gear Uses >> 5 >> Year (End)": "q63_turnoutGear63[4][2]",
  "Turnout Gear Uses >> 6 >> Type of Turnout Gear": "q63_turnoutGear63[5][0]",
  "Turnout Gear Uses >> 6 >> Circumstances of Use": "q63_turnoutGear63[5][1]",
  "Turnout Gear Uses >> 6 >> Year (End)": "q63_turnoutGear63[5][2]",
  "Turnout Gear Uses >> 7 >> Type of Turnout Gear": "q63_turnoutGear63[6][0]",
  "Turnout Gear Uses >> 7 >> Circumstances of Use": "q63_turnoutGear63[6][1]",
  "Turnout Gear Uses >> 7 >> Year (End)": "q63_turnoutGear63[6][2]",
  "Turnout Gear Uses >> 8 >> Type of Turnout Gear": "q63_turnoutGear63[7][0]",
  "Turnout Gear Uses >> 8 >> Circumstances of Use": "q63_turnoutGear63[7][1]",
  "Turnout Gear Uses >> 8 >> Year (End)": "q63_turnoutGear63[7][2]",
  "Turnout Gear Uses >> 9 >> Type of Turnout Gear": "q63_turnoutGear63[8][0]",
  "Turnout Gear Uses >> 9 >> Circumstances of Use": "q63_turnoutGear63[8][1]",
  "Turnout Gear Uses >> 9 >> Year (End)": "q63_turnoutGear63[8][2]",
  "Yes": "q22_yes",
  "No": "q23_no",
  "I don't know": "q76_iDont76",
  "If Yes then describe below the instances and frequency in which you would wear Turnout Gear when not responding to a call": "q24_ifYes",
  "Yes": "q26_yes26",
  "No": "q27_no27",
  "I don't know": "q77_iDont77",
  "Input Table >> Military Base 1 >> Type of Turnout Gear": "q62_typeA62[0][0]",
  "Input Table >> Military Base 1 >> Year (Start)": "q62_typeA62[0][1]",
  "Input Table >> Military Base 1 >> Year (End)": "q62_typeA62[0][2]",
  "Input Table >> Military Base 2 >> Type of Turnout Gear": "q62_typeA62[1][0]",
  "Input Table >> Military Base 2 >> Year (Start)": "q62_typeA62[1][1]",
  "Input Table >> Military Base 2 >> Year (End)": "q62_typeA62[1][2]",
  "Input Table >> Military Base 3 >> Type of Turnout Gear": "q62_typeA62[2][0]",
  "Input Table >> Military Base 3 >> Year (Start)": "q62_typeA62[2][1]",
  "Input Table >> Military Base 3 >> Year (End)": "q62_typeA62[2][2]",
  "Input Table >> Military Base 4 >> Type of Turnout Gear": "q62_typeA62[3][0]",
  "Input Table >> Military Base 4 >> Year (Start)": "q62_typeA62[3][1]",
  "Input Table >> Military Base 4 >> Year (End)": "q62_typeA62[3][2]",
  "Input Table >> Airport Fire 1 >> Type of Turnout Gear": "q62_typeA62[4][0]",
  "Input Table >> Airport Fire 1 >> Year (Start)": "q62_typeA62[4][1]",
  "Input Table >> Airport Fire 1 >> Year (End)": "q62_typeA62[4][2]",
  "Input Table >> Airport Fire 2 >> Type of Turnout Gear": "q62_typeA62[5][0]",
  "Input Table >> Airport Fire 2 >> Year (Start)": "q62_typeA62[5][1]",
  "Input Table >> Airport Fire 2 >> Year (End)": "q62_typeA62[5][2]",
  "Input Table >> Airport Fire 3 >> Type of Turnout Gear": "q62_typeA62[6][0]",
  "Input Table >> Airport Fire 3 >> Year (Start)": "q62_typeA62[6][1]",
  "Input Table >> Airport Fire 3 >> Year (End)": "q62_typeA62[6][2]",
  "Input Table >> Airport Fire 4 >> Type of Turnout Gear": "q62_typeA62[7][0]",
  "Input Table >> Airport Fire 4 >> Year (Start)": "q62_typeA62[7][1]",
  "Input Table >> Airport Fire 4 >> Year (End)": "q62_typeA62[7][2]",
  "Input Table >> Hazardous Materials 1 >> Type of Turnout Gear": "q62_typeA62[8][0]",
  "Input Table >> Hazardous Materials 1 >> Year (Start)": "q62_typeA62[8][1]",
  "Input Table >> Hazardous Materials 1 >> Year (End)": "q62_typeA62[8][2]",
  "Input Table >> Hazardous Materials 2 >> Type of Turnout Gear": "q62_typeA62[9][0]",
  "Input Table >> Hazardous Materials 2 >> Year (Start)": "q62_typeA62[9][1]",
  "Input Table >> Hazardous Materials 2 >> Year (End)": "q62_typeA62[9][2]",
  "Input Table >> Hazardous Materials 3 >> Type of Turnout Gear": "q62_typeA62[10][0]",
  "Input Table >> Hazardous Materials 3 >> Year (Start)": "q62_typeA62[10][1]",
  "Input Table >> Hazardous Materials 3 >> Year (End)": "q62_typeA62[10][2]",
  "Input Table >> Hazardous Materials 4 >> Type of Turnout Gear": "q62_typeA62[11][0]",
  "Input Table >> Hazardous Materials 4 >> Year (Start)": "q62_typeA62[12][1]",
  "Input Table >> Hazardous Materials 4 >> Year (End)": "q62_typeA62[13][2]",
  "Input Table >> Overhauling Work 1 >> Type of Turnout Gear": "q62_typeA62[12][0]",
  "Input Table >> Overhauling Work 1 >> Year (Start)": "q62_typeA62[12][1]",
  "Input Table >> Overhauling Work 1 >> Year (End)": "q62_typeA62[12][2]",
  "Input Table >> Overhauling Work 2 >> Type of Turnout Gear": "q62_typeA62[13][0]",
  "Input Table >> Overhauling Work 2 >> Year (Start)": "q62_typeA62[13][1]",
  "Input Table >> Overhauling Work 2 >> Year (End)": "q62_typeA62[13][2]",
  "Input Table >> Overhauling Work 3 >> Type of Turnout Gear": "q62_typeA62[14][0]",
  "Input Table >> Overhauling Work 3 >> Year (Start)": "q62_typeA62[14][1]",
  "Input Table >> Overhauling Work 3 >> Year (End)": "q62_typeA62[14][2]",
  "Input Table >> Overhauling Work 4 >> Type of Turnout Gear": "q62_typeA62[15][0]",
  "Input Table >> Overhauling Work 4 >> Year (Start)": "q62_typeA62[15][1]",
  "Input Table >> Overhauling Work 4 >> Year (End)": "q62_typeA62[15][2]",
  "Yes": "q30_yes30",
  "No": "q31_no31",
  "I don't know": "q32_iDont",
  "Turnout Gears Coating Details >> 1 >> Type of Turnout Gear": "q61_turnoutGears[0][0]",
  "Turnout Gears Coating Details >> 1 >> Coating Type": "q61_turnoutGears[0][1]",
  "Turnout Gears Coating Details >> 1 >> Manufacturer": "q61_turnoutGears[0][2]",
  "Turnout Gears Coating Details >> 1 >> Brand Name": "q61_turnoutGears[0][3]",
  "Turnout Gears Coating Details >> 1 >> Year (Start)": "q61_turnoutGears[0][4]",
  "Turnout Gears Coating Details >> 1 >> Year (End)": "q61_turnoutGears[0][5]",
  "Turnout Gears Coating Details >> 2 >> Type of Turnout Gear": "q61_turnoutGears[1][0]",
  "Turnout Gears Coating Details >> 2 >> Coating Type": "q61_turnoutGears[1][1]",
  "Turnout Gears Coating Details >> 2 >> Manufacturer": "q61_turnoutGears[1][2]",
  "Turnout Gears Coating Details >> 2 >> Brand Name": "q61_turnoutGears[1][3]",
  "Turnout Gears Coating Details >> 2 >> Year (Start)": "q61_turnoutGears[1][4]",
  "Turnout Gears Coating Details >> 2 >> Year (End)": "q61_turnoutGears[1][5]",
  "Turnout Gears Coating Details >> 3 >> Type of Turnout Gear": "q61_turnoutGears[2][0]",
  "Turnout Gears Coating Details >> 3 >> Coating Type": "q61_turnoutGears[2][1]",
  "Turnout Gears Coating Details >> 3 >> Manufacturer": "q61_turnoutGears[2][2]",
  "Turnout Gears Coating Details >> 3 >> Brand Name": "q61_turnoutGears[2][3]",
  "Turnout Gears Coating Details >> 3 >> Year (Start)": "q61_turnoutGears[2][4]",
  "Turnout Gears Coating Details >> 3 >> Year (End)": "q61_turnoutGears[2][5]",
  "Turnout Gears Coating Details >> 4 >> Type of Turnout Gear": "q61_turnoutGears[3][0]",
  "Turnout Gears Coating Details >> 4 >> Coating Type": "q61_turnoutGears[3][1]",
  "Turnout Gears Coating Details >> 4 >> Manufacturer": "q61_turnoutGears[3][2]",
  "Turnout Gears Coating Details >> 4 >> Brand Name": "q61_turnoutGears[3][3]",
  "Turnout Gears Coating Details >> 4 >> Year (Start)": "q61_turnoutGears[3][4]",
  "Turnout Gears Coating Details >> 4 >> Year (End)": "q61_turnoutGears[3][5]",
  "Yes": "q34_yes34",
  "No": "q35_no35",
  "I don't know": "q78_iDont78",
  "Turnout Gear Cleaning Details >> 1 >> Type of Turnout Gear": "q60_turnoutGear60[0][0]",
  "Turnout Gear Cleaning Details >> 1 >> Cleaning Location": "q60_turnoutGear60[0][1]",
  "Turnout Gear Cleaning Details >> 1 >> Year (Start)": "q60_turnoutGear60[0][2]",
  "Turnout Gear Cleaning Details >> 1 >> Years (End)": "q60_turnoutGear60[0][3]",
  "Turnout Gear Cleaning Details >> 2 >> Type of Turnout Gear": "q60_turnoutGear60[1][0]",
  "Turnout Gear Cleaning Details >> 2 >> Cleaning Location": "q60_turnoutGear60[1][1]",
  "Turnout Gear Cleaning Details >> 2 >> Year (Start)": "q60_turnoutGear60[1][2]",
  "Turnout Gear Cleaning Details >> 2 >> Years (End)": "q60_turnoutGear60[1][3]",
  "Turnout Gear Cleaning Details >> 3 >> Type of Turnout Gear": "q60_turnoutGear60[2][0]",
  "Turnout Gear Cleaning Details >> 3 >> Cleaning Location": "q60_turnoutGear60[2][1]",
  "Turnout Gear Cleaning Details >> 3 >> Year (Start)": "q60_turnoutGear60[2][2]",
  "Turnout Gear Cleaning Details >> 3 >> Years (End)": "q60_turnoutGear60[2][3]",
  "Turnout Gear Cleaning Details >> 4 >> Type of Turnout Gear": "q60_turnoutGear60[3][0]",
  "Turnout Gear Cleaning Details >> 4 >> Cleaning Location": "q60_turnoutGear60[3][1]",
  "Turnout Gear Cleaning Details >> 4 >> Year (Start)": "q60_turnoutGear60[3][2]",
  "Turnout Gear Cleaning Details >> 4 >> Years (End)": "q60_turnoutGear60[3][3]",
  "Turnout Gear Cleaning Details >> 5 >> Type of Turnout Gear": "q60_turnoutGear60[4][0]",
  "Turnout Gear Cleaning Details >> 5 >> Cleaning Location": "q60_turnoutGear60[4][1]",
  "Turnout Gear Cleaning Details >> 5 >> Year (Start)": "q60_turnoutGear60[4][2]",
  "Turnout Gear Cleaning Details >> 5 >> Years (End)": "q60_turnoutGear60[4][3]",
  "Turnout Gear Cleaning Details >> 6 >> Type of Turnout Gear": "q60_turnoutGear60[5][0]",
  "Turnout Gear Cleaning Details >> 6 >> Cleaning Location": "q60_turnoutGear60[5][1]",
  "Turnout Gear Cleaning Details >> 6 >> Year (Start)": "q60_turnoutGear60[5][2]",
  "Turnout Gear Cleaning Details >> 6 >> Years (End)": "q60_turnoutGear60[5][3]",
  "Turnout Gear Cleaning Details >> 7 >> Type of Turnout Gear": "q60_turnoutGear60[6][0]",
  "Turnout Gear Cleaning Details >> 7 >> Cleaning Location": "q60_turnoutGear60[6][1]",
  "Turnout Gear Cleaning Details >> 7 >> Year (Start)": "q60_turnoutGear60[6][2]",
  "Turnout Gear Cleaning Details >> 7 >> Years (End)": "q60_turnoutGear60[6][3]",
  "Turnout Gear Cleaning Details >> 8 >> Type of Turnout Gear": "q60_turnoutGear60[7][0]",
  "Turnout Gear Cleaning Details >> 8 >> Cleaning Location": "q60_turnoutGear60[7][1]",
  "Turnout Gear Cleaning Details >> 8 >> Year (Start)": "q60_turnoutGear60[7][2]",
  "Turnout Gear Cleaning Details >> 8 >> Years (End)": "q60_turnoutGear60[7][3]",
  "Turnout Gear Cleaning Details >> 9 >> Type of Turnout Gear": "q60_turnoutGear60[8][0]",
  "Turnout Gear Cleaning Details >> 9 >> Cleaning Location": "q60_turnoutGear60[8][1]",
  "Turnout Gear Cleaning Details >> 9 >> Year (Start)": "q60_turnoutGear60[8][2]",
  "Turnout Gear Cleaning Details >> 9 >> Years (End)": "q60_turnoutGear60[8][3]",
  "Yes": "q38_yes38",
  "No": "q39_no39",
  "I don't know": "q40_iDont40",
  "Breathing Equipment Detail >> 1 >> Type of Breathing Equipment": "q59_breathingEquipment[0][0]",
  "Breathing Equipment Detail >> 1 >> Manufacturer": "q59_breathingEquipment[0][1]",
  "Breathing Equipment Detail >> 1 >> Call Type Used": "q59_breathingEquipment[0][2]",
  "Breathing Equipment Detail >> 1 >> Years (Start)": "q59_breathingEquipment[0][3]",
  "Breathing Equipment Detail >> 1 >> ": "q59_breathingEquipment[0][4]",
  "Breathing Equipment Detail >> 2 >> Type of Breathing Equipment": "q59_breathingEquipment[1][0]",
  "Breathing Equipment Detail >> 2 >> Manufacturer": "q59_breathingEquipment[1][1]",
  "Breathing Equipment Detail >> 2 >> Call Type Used": "q59_breathingEquipment[1][2]",
  "Breathing Equipment Detail >> 2 >> Years (Start)": "q59_breathingEquipment[1][3]",
  "Breathing Equipment Detail >> 2 >> ": "q59_breathingEquipment[1][4]",
  "Breathing Equipment Detail >> 3 >> Type of Breathing Equipment": "q59_breathingEquipment[2][0]",
  "Breathing Equipment Detail >> 3 >> Manufacturer": "q59_breathingEquipment[2][1]",
  "Breathing Equipment Detail >> 3 >> Call Type Used": "q59_breathingEquipment[2][2]",
  "Breathing Equipment Detail >> 3 >> Years (Start)": "q59_breathingEquipment[2][3]",
  "Breathing Equipment Detail >> 3 >> ": "q59_breathingEquipment[2][4]",
  "Breathing Equipment Detail >> 4 >> Type of Breathing Equipment": "q59_breathingEquipment[3][0]",
  "Breathing Equipment Detail >> 4 >> Manufacturer": "q59_breathingEquipment[3][1]",
  "Breathing Equipment Detail >> 4 >> Call Type Used": "q59_breathingEquipment[3][2]",
  "Breathing Equipment Detail >> 4 >> Years (Start)": "q59_breathingEquipment[3][3]",
  "Breathing Equipment Detail >> 4 >> ": "q59_breathingEquipment[3][4]",
  "Breathing Equipment Detail >> 5 >> Type of Breathing Equipment": "q59_breathingEquipment[4][0]",
  "Breathing Equipment Detail >> 5 >> Manufacturer": "q59_breathingEquipment[4][1]",
  "Breathing Equipment Detail >> 5 >> Call Type Used": "q59_breathingEquipment[4][2]",
  "Breathing Equipment Detail >> 5 >> Years (Start)": "q59_breathingEquipment[4][3]",
  "Breathing Equipment Detail >> 5 >> ": "q59_breathingEquipment[4][4]",
  "Yes": "q43_yes43",
  "No": "q81_no81",
  "I don't know": "q82_iDont82",
  "If yes then to the best of your knowledge please describe i the type of call ii the garments you would typically wear instead of Turnout Gear iii the manufacturer of those garments and iv the years of you used those garments": "q80_ifYes80",
  "Yes": "q83_yes83",
  "No": "q84_no84",
  "I don't know": "q85_iDont85",
  "If yes then to the best of your knowledge please describe the garments you wore under your Turnout Gear including the manufacturer of the garments and the years of use": "q45_ifYes45",
  "Yes": "q87_yes87",
  "No": "q88_no88",
  "If no then identify the injury disease and damages that you allege resulted from exposure to PFAS from your use of Turnout Gear": "q47_ifNo",
  "Yes": "q49_yes49",
  "No": "q50_no50",
  "Yes": "q52_yes52",
  "No": "q53_no53",
  "If yes, with whom did you consult ?": "q90_ifYes90",
  "Signature of Plaintiff": "q55_signatureOf",
  "Print Name": "q56_printName",
  "Date": "q57_date[month]/q57_date[day/q57_date[year]",
  // 👉 Add more mappings based on your sheet & form fields
};

function readExcel(filePath) {
  const workbook = XLSX.readFile(filePath);
  const sheetName = workbook.SheetNames[0];
  const worksheet = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]);
  return worksheet;
}

async function fillForm(page, row) {
  for (const [header, fieldName] of Object.entries(FIELD_MAP)) {
    const value = row[header];
    if (!value) continue;

    const selector = `[name="${fieldName}"]`;
    try {
      await page.waitForSelector(selector, { timeout: 2000 });
      await page.evaluate(
        (sel) => { document.querySelector(sel).value = ""; },
        selector
      );
      await page.type(selector, value.toString(), { delay: 50 });
    } catch {
      console.warn(`⚠️ Could not fill field: ${header} (${fieldName})`);
    }
  }
}

async function main() {
  const rows = readExcel(XLSX_FILE);
  console.log(`Found ${rows.length} submissions in Excel`);

  const browser = await puppeteer.launch({ headless: false }); // show browser for debugging
  const page = await browser.newPage();

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    console.log(`Submitting row ${i + 1}:`, row);

    await page.goto(FORM_URL, { waitUntil: "networkidle2" });

    await fillForm(page, row);

    // Submit
    await page.click('button[type="submit"]');
    await page.waitForNavigation({ waitUntil: "networkidle2" });
    console.log(`✅ Row ${i + 1} submitted`);

    await page.waitForTimeout(2000); // cooldown
  }

  await browser.close();
}

main().catch(console.error);
